"""
This file contains functions for ploting data from log files generated by design comparison based approaches:
design_comparison.py is an example for cs_amp from a pre simulated look up table


"""
import matplotlib.pyplot as plt
import numpy as np
import pickle
import matplotlib.colors

def print_best_sample(fname):
    with open(fname, 'rb') as f:
        read_data = pickle.load(f)

    assert {'data_set_list', 'cost_set_list'}.issubset(read_data.keys())


    data_set_list = read_data['data_set_list']
    cost_set_list = read_data['cost_set_list']

    for i in range(len(cost_set_list)):
        print("[Info] @step: {} -> design: {} -> cost: {}" .format(i, data_set_list[i][0], cost_set_list[i][0]))

def main():
    print_best_sample('genetic_nn/log_files/two_stage_logbook.pickle')
    plt.show()

if __name__ == '__main__':
    main()